function mdc; mkdir -p $argv; and cd $argv; end

alias .. "cd ../"
alias ... "cd ../../"

alias g "git"
alias ga "git add"
alias gaa "git add -A"
alias gb "git branch -vva"
alias gc "git clone"
alias gco "git checkout"
alias gd "git diff"
alias gp "git pull"
alias gst "git status"
alias m "make"
alias mc "make clean"
alias md "mkdir -p"
alias mm "make -j32"
alias ua "uname -a"
alias v "vim"
